service: introductions-bot

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-prune-plugin
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
  
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - ${file(./local_config.yml):tokenSecretArn}
  stackTags:
    owner: "skill-software-devops"
    application: "introductions-bot"


functions:
  app:
    handler: wsgi.handler
    memorySize: 128
    events:
      - httpApi: GET /
      - httpApi: POST /
    environment:
      SECRET_ARN: ${file(./local_config.yml):tokenSecretArn}
